debug: false
spring:
  application:
    name: svr-reg

server:
  port: 8000
management:
  server:
    port: 8001

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
    metadata-map:
      VERSION: 1.0.0
    prefer-ip-address: false
    hostname: ${MY_POD_NAME}.svr-reg
  client:
    # 检索服务选项，注册中心不需要检索服务
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    # 注册中心将自己作为客户端来尝试注册自己，注册中心集群环境下需开启此配置
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://svr-reg-0.svr-reg:8000/eureka/,http://svr-reg-1.svr-reg:8000/eureka/} #这里在部署的时候会使用环境变量替换 EUREKA_DEFAULT_ZONE值
    registryFetchIntervalSeconds: 10
    disable-delta: true
    server:
      evictionIntervalTimerInMs: 4000
      enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:false}
