apiVersion: apps/v1
kind: Deployment
metadata:
  name: svr-gateway
  labels:
    app: svr-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svr-gateway
  template:
    metadata:
      labels:
        app: svr-gateway
    spec:
      containers:
        - name: svr-gateway
          image: hub.atguigu.com/library/svr-gateway:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              # cpu: 100m
              memory: 500Mi
            requests:
              # cpu: 100m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svr-gateway
  labels:
    app: svr-gateway
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32222
  selector:
    app: svr-gateway
